name: untitled4
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:

    sdk: flutter

  #UI
  cupertino_icons: ^1.0.2

  #FIREBASE
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  google_sign_in: ^5.4.2
  #  firebase_database: ^10.2.3
  #  firebase_storage: ^11.2.4

  provider: ^6.0.1

  #SCREEN WIDGETS
  animated_splash_screen: ^1.3.0
  introduction_screen: ^3.1.9
  lottie: ^2.4.0

  #LOCATION
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:

    - assets/
    - assets/google_logo.png
    - assets/password_icon.png
    - assets/email_icon.png
    - assets/paw_image.png
    - assets/eye_password.png
    - assets/introduction_screen/img_1.png
    - assets/introduction_screen/img_2.png
    - assets/introduction_screen/img_3.png
    - assets/splash_screen/splash.png
    - assets/splash_screen/paw_icon.png
    - assets/gif/astronaut-cat.gif